config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/practice', to: 'practice_pages#practice'
  resources :practice_results, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/practice_result.rb
class PracticeResult < ApplicationRecord
  before_validation :set_name_if_nameless

  validates :name, presence: true, length: {maximum: 30}
  validates :score, presence: true
  private
  def set_name_if_nameless
    self.name = "名無し" if name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/practice_pages_controller.rb
class PracticePagesController < ApplicationController
  def practice
    @practice_result = PracticeResult.new
  end
end

app/controllers/practice_results_controller.rb
class PracticeResultsController < ApplicationController
  def index
    @practice_results = PracticeResult.all.order(score: :desc).limit(10)
  end

  def create
    @practice_result = PracticeResult.new(practice_result_params)
    @practice_result.save!
    redirect_to practice_results_path
  end

  private

  def practice_result_params
    params.require(:practice_result).permit(:name, :score)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursorPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="app-title.navbar navbar-expand-md navbar-light bg-dark">
      <div class="navbar-brand">
        <%= link_to "Cursor Practice", root_path, class: "ml-3 header-titile" %>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/practice_pages/practice.html.erb
<%= javascript_include_tag 'practice.js' %>

<%= audio_tag('bingo.mp3',id: 'js-bingo-audio') %>

<div class="mx-auto w-50 text-center mt-5">
  <h4 class="text-left">Time: <span id="js-time-view">30</span></h4>
  <h4 class="text-left">Score: <span id="js-score-view">0</span></h4>

  <%= image_tag 'practice_images/start', id: 'js-question-image', size: '500x380'%>
  <h3 id="js-question-guide" class="mt-3 mb-4">spaceキーで開始</h4>

  <div id="js-result-element" style="display: none;">
    <%= form_with model: @practice_result, url: practice_results_path, local: true do |f| %>
      <%= f.text_field :name, maxlength: 30, placeholder: "名前を入力" %>
      <%= f.hidden_field :score, maxlength: 10, value: 0, id: 'js-score-field'%>
      <%= f.submit class: 'btn btn-dark', value: 'ランキング登録' %>
    <% end %>

    <span id="js-retry-btn" class="btn btn-dark mt-2">リトライ</span>
  </div>
</div>

app/views/practice_results/index.html.erb
<h1 class="mt-5">ランキング</h1>

<div class="mt-3">
  <table class="table table-hover w-75">
    <thead class="thead-default">
      <tr>
        <th>順位</th>
        <th>名前</th>
        <th>スコア</th>
      </tr>
    </thead>

    <tbody>
      <% @practice_results.each.with_index(1) do |practice_result, rank| %>
        <tr >
          <% if rank == 1 %>
            <th><i class="fas fa-crown"></i> <%= rank %></th>
          <% elsif rank == 2 %>
            <th><i class="fas fa-chess-king"></i> <%= rank %></th>
          <% elsif rank == 3 %>
            <th><i class="fas fa-chess-knight"></i> <%= rank %></th>
          <% else %>
            <th><i class="fas fa-running"></i> <%= rank %></th>
          <% end %>
          <td><%= practice_result.name %></td>
          <td><%= practice_result.score %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

<div class="nav justify-content-center mb-3">
  <%= link_to "戻る", root_path, class: "nav-link back-link" %>
</div>

app/views/static_pages/top.html.erb
<h1 class="mt-5">カーソルキーからの卒業</h1>
<p class="mt-3 mb-3">
  カーソルの移動にはショートカットキーを利用するべきです。<br>
  ショートカットキーを利用することで、あなたはホームポジションを維持できます。<br>
  Cursor Placticeでショートカットの練習を始めましょう！<br>
</p>
<p>※このアプリケーションでは効果音が再生されます</p>

<table class="table table-bordered w-50" >
  <thead>
    <tr>
      <th scope="col">移動方向</th>
      <th scope="col">ショートカットキー</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">↑</th>
      <td>Ctrl + P</td>
    </tr>
    <tr>
      <th scope="row">←</th>
      <td>Ctrl + B</td>
    </tr>
    <tr>
      <th scope="row">→</th>
      <td>Ctrl + F</td>
    </tr>
    <tr>
      <th scope="row">↓</th>
      <td>Ctrl + N</td>
    </tr>
  </tbody>
</table>

<div class="mt-3">
  <%= link_to 'スタート', practice_path, class: 'btn btn-dark ml-2' %>
  <%= link_to 'ランキング', practice_results_path, class: 'btn btn-dark ml-2' %>
</div>